from setuptools import setup, find_packages

setup(
    name="shadoweye",
    version="3.1.0",
    description="Multi-Tool OSINT Framework for Termux",
    long_description=open('README.md', encoding='utf-8').read(),
    long_description_content_type="text/markdown",
    author="lixynhay",
    author_email="",
    url="https://github.com/lixynhay/ShadowEye",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "rich>=13.0.0",
        "httpx>=0.27.0",
        "requests>=2.31.0",
        "holehe>=1.0.0",
        "maigret>=0.4.0",
        "phonenumbers>=8.13.0",
        "python-whois>=0.9.0",
        "dnspython>=2.6.0",
        "exifread>=3.0.0",
        "PySocks>=1.7.0",
        "colorama>=0.4.6",
        "beautifulsoup4>=4.12.0",
        "lxml>=5.0.0",
        "requests-futures>=1.0.0",
        "stem>=1.8.0",
    ],
    entry_points={
        "console_scripts": [
            "shadoweye=osint_toolkit.cli:main",
        ],
    },
    python_requires=">=3.10",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Console",
        "Intended Audience :: Information Technology",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Security",
        "Operating System :: POSIX :: Linux",
    ],
    keywords="osint security termux email username phone domain exif",
)
